%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------
# (Load/Save Atlas settings are commented out)
File.version: "1.0"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Intrinsic calibration for DJI Mini 3
Camera1.fx: 539.0        # Estimated focal length in pixels (horizontal)
Camera1.fy: 463.0        # Estimated focal length in pixels (vertical)
Camera1.cx: 376.0        # Principal point x (assumed at image center)
Camera1.cy: 240.0        # Principal point y (assumed at image center)

# Distortion coefficients (assuming minimal distortion)
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

# Image size and other camera parameters (common to the sensor)
Camera.width: 752
Camera.height: 480
Camera.fps: 20
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# (Stereo parameters removed for a monocular configuration)
#--------------------------------------------------------------------------------------------

#--------------------------------------------------------------------------------------------
# IMU Parameters (if used)
#--------------------------------------------------------------------------------------------
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.01486554, -0.99988093,  0.00414030, -0.02164015,
         0.99955725,  0.01496721,  0.02571553, -0.06467699,
        -0.02577444,  0.00375619,  0.99966073,  0.00981073,
         0.0,         0.0,         0.0,         1.0]
IMU.NoiseGyro: 1.7e-04
IMU.NoiseAcc: 2.0e-03
IMU.GyroWalk: 1.9393e-05
IMU.AccWalk: 3.0e-03
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures: 1200
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0

